### ISSUE TITLE
A question about the function “deleteHashEntryElement”

### ISSUE THREAD

**Issue by lelleMU** [nachtmar/VoxelHashing#15]
When I read the code, I had a question about the code in the line 791 in VoxelUtilHashSDF.h
`prev.offset = curr.offset;`
As long as I am concered, in this part, you want the previous hash entry to point to the next and next hash entry so that you skip the current entry to delete it from the linked list.
So in my view the code should be like
`prev.offset += curr.offset;`
for example, the `offset` of previous entry is 1 and it points to current entry which one we want to delete and the `offset` of the current entry is 2 which points to the next valid entry then we need to fix the `offset`  of the previous entry to 3 so that we can skip the current entry and point it to the next valid entry. 
That's what I think, I am not sure if I get the right understanding of your code, I hope you can make it clear to me. THX!

**Comment by lelleMU** [comment]
well , I find I made a mistake

**Comment by zyuanbing** [comment]
> When I read the code, I had a question about the code in the line 791 in VoxelUtilHashSDF.h
> `prev.offset = curr.offset;`
> As long as I am concered, in this part, you want the previous hash entry to point to the next and next hash entry so that you skip the current entry to delete it from the linked list.
> So in my view the code should be like
> `prev.offset += curr.offset;`
> for example, the `offset` of previous entry is 1 and it points to current entry which one we want to delete and the `offset` of the current entry is 2 which points to the next valid entry then we need to fix the `offset` of the previous entry to 3 so that we can skip the current entry and point it to the next valid entry.
> That's what I think, I am not sure if I get the right understanding of your code, I hope you can make it clear to me. THX!

Hi, have you get the test data, and how to get it?
